### ISSUE TITLE
Wiki Home Page

### ISSUE THREAD

**Issue by PedroKim** [JasonStaubach/Spotify-Clone#2]
# Wiki Home Page
- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [ ] Correctly formatted
  - [ ] each wiki page is listed in bullet points
  - [x] all links route the correct page

## Comments
- refer to [Bluebird Wiki](https://github.com/appacademy/bluebird/wiki) for correct formatting.

**Comment by JasonStaubach** [comment]
added bullet points
